name: Pull Request To Dev
run-name: Run Integration Tests
on:
  pull_request:
    branches:
      - 'dev'
jobs:
  integration_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: cd src/app/
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run app
        run: dotnet run --no-restore
      - name: Test GET-request
        run: |
          ANSW=$(curl http://127.0.0.1:5000/)
          if [ "$ANSW" != "Hello, World!" ]; then
          exit 1
          else
          echo "Integration Test PASS"
          fi
