name: Pull Request To Dev
run-name: Run Integration Tests
on:
  pull_request:
    branches:
      - 'dev'
jobs:
  integration_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x', '6.0.x']
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-verison }}
        uses: actions/setup-dotnet@v3
      - name: Install dependencies
        run: dotnet restore /src/app/app.csproj
      - name: Build
        run: dotnet build /src/app/app.csproj  --no-restore
      - name: Run app
        run: dotnet run ./src/app/app.csproj --no-restore
      - name: Test GET-request
        run: |
          ANSW=$(curl http://127.0.0.1:5000/)
          if [ "$ANSW" != "Hello, World!" ]; then
          exit 1
          else
          echo "Integration Test PASS"
          fi
